apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-consumer-client
  labels:
    app: kafka-examples
    purpose: examples
    type: performance
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: kafka-client
          image: confluentinc/cp-server:7.0.1
          env:
            - name: BOOTSTRAP_SERVERS
              value: PLAINTEXT://confluentinc-cp-kafka:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "confluentinc-cp-zookeeper:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://confluentinc-cp-zookeeper:5556
          command:
            - sh
            - -c
            - "kafka-consumer-perf-test \
               --topic ssl-producer \
               --broker-list $BOOTSTRAP_SERVERS \
               --from-latest \
               --messages 5000000 \
               --consumer.config /etc/kafka/consumer.properties \
               --group $HOSTNAME \
               --timeout 9000000"
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: '1'
              memory: 1Gi
      restartPolicy: Never
