apiVersion: v1
data:
  perf-script.sh: |
    #!/usr/bin/env bash
    for i in 1000 2000 5000 10000 20000 30000 40000; do
      echo ""
      echo $i
      kafka-producer-perf-test \
        --topic ssl-perf-test \
        --num-records $((10*$i))\
        --record-size 1000\
        --throughput $i \
        --producer.config $CONFIG_PATH \
        --producer-props acks=all \
        bootstrap.servers=$BOOTSTRAP_SERVERS \
        buffer.memory=67108864 \
        batch.size=64000
    done;
kind: ConfigMap
metadata:
  labels:
    app: kafka-examples
    purpose: examples
    type: performance
  name: kafka-single-producer-perf-script
...
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-single-producer-client
  labels:
    app: kafka-examples
    purpose: examples
    type: performance
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: kafka-client
          image: confluentinc/cp-server:7.2.1
          env:
            - name: BOOTSTRAP_SERVERS
              value: PLAINTEXT://confluentinc-cp-kafka:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "confluentinc-cp-zookeeper:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://confluentinc-cp-zookeeper:5556
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: '1'
              memory: 1Gi
      restartPolicy: Never
